name: Deploy Node.js Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'  

    - name: Install dependencies
      run: |
        cd engine-service && npm install
        cd ../gps-data-service && npm install
        cd ../schedule-service && npm install
        cd ../train-service && npm install
        cd ../train-tracking-service && npm install
        cd ../user-service && npm install

    - name: Build projects
      run: |
        cd engine-service && npm run build || true
        cd ../gps-data-service && npm run build || true
        cd ../schedule-service && npm run build || true
        cd ../train-service && npm run build || true
        cd ../train-tracking-service && npm run build || true
        cd ../user-service && npm run build || true

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        rsync -avz -e "ssh -i $PRIVATE_KEY" ./engine-service $USER@$HOST:/home/$USER/engine-service
        rsync -avz -e "ssh -i $PRIVATE_KEY" ./gps-data-service $USER@$HOST:/home/$USER/gps-data-service
        rsync -avz -e "ssh -i $PRIVATE_KEY" ./schedule-service $USER@$HOST:/home/$USER/schedule-service
        rsync -avz -e "ssh -i $PRIVATE_KEY" ./train-service $USER@$HOST:/home/$USER/train-service
        rsync -avz -e "ssh -i $PRIVATE_KEY" ./train-tracking-service $USER@$HOST:/home/$USER/train-tracking-service
        rsync -avz -e "ssh -i $PRIVATE_KEY" ./user-service $USER@$HOST:/home/$USER/user-service

        ssh -i "$PRIVATE_KEY" "$USER@$HOST" << 'EOF'
          cd /home/$USER/engine-service
          npm install
          pm2 stop engine-service || true
          pm2 delete engine-service || true
          pm2 start app.js --name engine-service

          cd /home/$USER/gps-data-service
          npm install
          pm2 stop gps-data-service || true
          pm2 delete gps-data-service || true
          pm2 start app.js --name gps-data-service

          cd /home/$USER/schedule-service
          npm install
          pm2 stop schedule-service || true
          pm2 delete schedule-service || true
          pm2 start app.js --name schedule-service

          cd /home/$USER/train-service
          npm install
          pm2 stop train-service || true
          pm2 delete train-service || true
          pm2 start app.js --name train-service

          cd /home/$USER/train-tracking-service
          npm install
          pm2 stop train-tracking-service || true
          pm2 delete train-tracking-service || true
          pm2 start app.js --name train-tracking-service

          cd /home/$USER/user-service
          npm install
          pm2 stop user-service || true
          pm2 delete user-service || true
          pm2 start app.js --name user-service

          pm2 save
        EOF
