name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to the branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH host key
      run: |
        ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Services
      run: |
        ssh ec2-user@${{ secrets.AWS_HOST }} << 'EOF'
        export MONGO_URI=${{ secrets.MONGO_URI }}
        
        cd ~/SriLankan-Railway-Live-Train-Tracking-API/api-gateway
        git pull origin main
        npm install
        pm2 restart index.js --name api-gateway

        cd ~/SriLankan-Railway-Live-Train-Tracking-API/engine-service
        git pull origin main
        npm install
        pm2 restart server.js --name engine-service

        cd ~/SriLankan-Railway-Live-Train-Tracking-API/gps-data-service
        git pull origin main
        npm install
        pm2 restart server.js --name gps-data-service

        cd ~/SriLankan-Railway-Live-Train-Tracking-API/schedule-service
        git pull origin main
        npm install
        pm2 restart server.js --name schedule-service

        cd ~/SriLankan-Railway-Live-Train-Tracking-API/train-service
        git pull origin main
        npm install
        pm2 restart server.js --name train-service

        cd ~/SriLankan-Railway-Live-Train-Tracking-API/train-tracking-service
        git pull origin main
        npm install
        pm2 restart server.js --name train-tracking-service

        cd ~/SriLankan-Railway-Live-Train-Tracking-API/user-service
        git pull origin main
        npm install
        pm2 restart server.js --name user-service
        
        EOF
